site_name: 'example-recommendation-service-docs'

nav:
  - Home: index.md
  - API Reference: api.md
  - Getting Started: getting-started.md

#docs_dir: documentation # Uncomment and set if your docs are in a different directory
theme:
  name: 'material'
plugins:
  - techdocs-core